export const themes = [
  {
    id: 1,
    name: "programming 💻",
    words: [
      "javascript",
      "html",
      "css",
      "algoritmo",
      "logica",
      "technology",
      "php",
      "java",
      "python",
      "array",
      "django",
      "flask",
      "ruby",
      "reactjs",
      "jquery",
      "mobile",
      "lavarel",
      "nodejs",
      "webpack",
      "spring",
      "bootsrap",
      "it",
      "arduino",
      "flutter",
      "desktop",
      "web",
      "devops",
      "developer",
      "software",
    ],
  },
  {
    id: 2,
    name: "animals 🐶",
    words: [
      "giraffe",
      "dog",
      "cat",
      "lion",
      "monkey",
      "elephant",
      "rhinoceros",
      "capybara",
      "anteater",
      "hippopotamus",
      "zebra",
      "horse",
      "chicken",
      "pig",
      "rabbit",
      "bull",
      "cow",
      "frog",
      "rat",
      "language",
      "sheep",
      "bootstrap",
      "tiger",
      "goat",
      "bear",
      "ferret",
      "tapir",
      "donkey",
      "squirrel",
      "lemur",
    ],
  },
  {
    id: 3,
    name: "countries 🌍",
    words: [
      "Argentina",
      "Angola",
      "Chile",
      "China",
      "Brazil",
      "Canada",
      "Mexico",
      "Germany",
      "Italy",
      "Japan",
      "France",
      "Netherlands",
      "Peru",
      "Australia",
      "England",
      "Panama",
      "Russia",
      "Uruguay",
      "Belgium",
      "Cameroon",
      "Egypt",
      "Iran",
      "Scotland",
      "Thailand",
      "Colombia",
      "Denmark",
      "Qatar",
      "Norway",
      "Jamaica",
      "lemur",
    ],
  },
  {
    id: 4,
    name: "fruits 🍓",
    words: [
      "pear",
      "apple",
      "avocado",
      "tomato",
      "strawberry",
      "blackberry",
      "banana",
      "kiwi",
      "tangerine",
      "orange",
      "acerola",
      "starfruit",
      "cherry",
      "coconut",
      "fig",
      "guava",
      "currant",
      "jabuticaba",
      "jackfruit",
      "lemon",
      "papaya",
      "Scotland",
      "mango",
      "passion fruit",
      "watermelon",
      "peach",
      "surinam cherry",
      "cashew fruit",
      "grape",
    ],
  },
  {
    id: 5,
    name: "sports ⚽",
    words: [
      "capoeira",
      "football",
      "volleyball",
      "boxing",
      "judo",
      "karate",
      "swimming",
      "athletics",
      "canoeing",
      "equestrianism",
      "rugby",
      "sailing",
      "basketball",
      "baseball",
      "fencing",
      "tennis",
      "surfing",
      "handball",
      "bowling",
      "badminton",
      "skiing",
      "golf",
      "crossfit",
      "biribol",
      "skateboarding",
      "motorcycling",
      "skating",
      "handball",
      "dance",
      "hockey",
    ],
  },
  {
    id: 6,
    name: "objects 🪑",
    words: [
      "abacus",
      "needle",
      "bank",
      "chair",
      "table",
      "flute",
      "spoon",
      "sofa",
      "flag",
      "bed",
      "wardrobe",
      "padlock",
      "notebook",
      "flip-flop",
      "dice",
      "rubber band",
      "knife",
      "cage",
      "napkin",
      "clothes",
      "screw",
      "wig",
      "picture frame",
      "vacuum cleaner",
      "razor",
      "broom",
      "microphone",
      "mask",
      "hammer",
      "book",
    ],
  },
];
